### ISSUE TITLE
Codim() in Entity

### ISSUE THREAD

**Issue by hiptmair** [craffael/lehrfempp#1]
Does an entity really have a co-dimension. Co-dimension is a relative concept, only dimension is absolute. 

Therefore I think the method Codim() could be replaced with ``virtual unsigned int Dim(void) const''. Of course. in principle the dimension can also be extracted from the RefEl and, maybe, we should drop that Codim() function without replacement.  If Codim() is kept a function WorldDim() is probably required, too. All these functions are duplicated in the Geometry() object anyway. 

My proposal: remove Codim() function

**Comment by craffael** [comment]
I agree with you: We could try to drop the concept of the codimension which would make the code even more accessible. Using the codimension instead of the dimension is mainly syntactic sugar. E.g. to get all elements of a mesh one can write `mesh.Entities(0)` instead of `mesh.Entities(mesh.DimMesh())`. Similary, to get the entities needed for boundary integrals one can write `mesh.Entities(1)` instead of `mesh.Entities(mesh.DimMesh() - 1)`. Of course iterating over all nodes is much easier, in this case. It is `mesh.Entities(mesh.DimMesh())` vs `mesh.Entities(0)`. But my experience has been that FEM codes work far more with elements (codim=0) or codim=1 entities than with nodes.

I'm fine with removing the codimension concept altogether even though I will have to type a bit more :)

**Comment by hiptmair** [comment]
The concept of codimension is ok and poses no challenges in terms of understanding. We should keep it, also because my current course design heavily relies on it.
