### ISSUE TITLE
index_ data member for Entity base class

### ISSUE THREAD

**Issue by hiptmair** [craffael/lehrfempp#10]
Probably it is a good idea that the base class mesh:Entity already has an `index_` data member, because this is needed for all Entity types ever created inside LehrFEM++.

This can also help avoid casts.

**Comment by craffael** [comment]
I'm not sure I understand your proposal: Are you suggesting to put an `index_` member into the interface class `lf::mesh::Entity`?

I also want to point out, that it is in fact not needed to have an `index_` member. I know that the current implementation has such a member, but I could also replace it with pointer arithmetic, i.e. in order to calculate the index of an element (codim=0) `e` I could calculate `&e - &mesh.entities0_[0]` to get the index :)

Finally I should also mention that [over the last decade many programmers have realized that is often a bad idea to use inheritance to implement behavior](https://en.wikipedia.org/wiki/Composition_over_inheritance) (e.g. putting an `index_` member into a base class and inherit from it). Nowadays in the object-oriented community, inheritance is mostly used for interfaces, that is classes that consist exclusively of pure virtual functions.

**Comment by hiptmair** [comment]
Ok, I acknowledge your expertise!
