### ISSUE TITLE
Do not use char for numbers

### ISSUE THREAD

**Issue by hiptmair** [craffael/lehrfempp#101]
There is no reason to use `char` instead of `unsigned int` for numbers like dimensions. Rather, it is a nuisance, because out via `cout` looks strange. 

I suggest that we convert all `char` types used for small numbers to `unsigned int`.

**Comment by craffael** [comment]
Well the only reason for using `char` would be that it is 8 bits instead of 32 bits, so converting char -> int will lead to speed penalty, but I think it will be small. On the other hand we can just write 
````
char c=5;
std::cout << +c;
```
to output c as a number. But I don't mind changing all `char -> unsigned int`, I should have time on the weekend.

**Comment by hiptmair** [comment]
I have merged the "char-free" version into the master branch.
