### ISSUE TITLE
Member function RelativeOrientation() for Entity

### ISSUE THREAD

**Issue by hiptmair** [craffael/lehrfempp#11]
_Orientation_ is a fundamental property of the Entities of cellular complexes (a generatlization of FE meshes used in algebraic topology). We have to define what is meant by the intrinsic orientation of any Entity:

- Every vertex has orientation +1
- An edge is oriented by specifying an ordering of its vertices; we use the ordering given by the `SubEntities()` method
- A cell is oriented by the ordering of its vertices given by the `SubEntities()` method.

The ordering of the vertices of an entity also induces an ordering of the vertices of all sub-entities, except for those of the largest co-dimension. This is called the induced orientation.

Once an orientation for each entity is specified, we can introduce the relative orientation of sub-entities: +1 is intrinsic and induced orientation match, -1 otherwise. 

Relaitve orientations should be returned by the member function `std::vector<Orientation> RelativeOrientation(char codim) const`

**Comment by craffael** [comment]
I mostly agree, the only point where I disagree is the possible values of the relative orientation. For 2d meshes it makes of course sense to only define two states, but for 3D meshes it doesn't help much if we know that the relative orientation is -1. We would still have to compare the coordinates of the nodes to define the basis functions.

# Suggestion:
Let `e` be an element and let `f` be a codim=1 sub-entity of `e` (face). I would then define the relative orientation `o` of `f` to be a mapping that maps the induced orientation to the intrinsic orientation, i.e. `o` would be a permutation of the nodes. If `o` is the identity, the intrinsic and induced orientation match.

The class Orientation could look for example as follows:
```
template<unsigned char num_nodes>
class Orientation {
public:
  bool IsIdentity();
  unsigned char eval(unsigned char i);
  Orientation inverse();
}
```

Final Remark: If the face is a quadrilateral, the group of all permutation is lightly too large because not all possible permutations are possible. In fact the group of all permutations of size 4 is 24, but the number of possible Orientations is only 8... Maybe there is still a better solution...?

**Comment by hiptmair** [comment]
In topology relative orientation is a map {Entities} x {Subentities of next higher co-dimension} -> {-1,0,1} , namely the incidence relation of the graph underlying the oriented complex. We have to stick with this established definition. I am going to write this method later.

**Comment by craffael** [comment]
Of course the relative orientation can be implemented like this and then it solves a few important problems, especially the construction FEM basis functions. However it does this only in 2D, I don't see how it can be useful in 3D, but maybe I misunderstand something?

**Comment by hiptmair** [comment]
Topological orientation now implemented as a method of the Entity interface.
