### ISSUE TITLE
Checking arguments of functions/constructors in lf::uscalfe

### ISSUE THREAD

**Issue by hiptmair** [craffael/lehrfempp#118]
Dangerous: A finite element space may not have definitions of a reference element for all entity types, maybe not even for all cell types. In this case `UniformScalarFESpace::ShapeFunctionLayout()` will retrurn a `nullptr`. However, this pointer is often used without checking whether it is valid. 

Corresponding assertions should be added. For instance, whenever a `PrecomputedScalarReferenceFiniteElement` is built, the pointer to the `ScalarReferenceFiniteElement` should be tested.

**Comment by craffael** [comment]
Good point. Instead of returning null pointers I would actually suggest to solve this via the ASSERT's already present but commented out in `uniform_scalar_fe_space.h`.
Advantage:
- If somebody calls `UniformScalarFESpace::ShapeFunctionLayout()` he can be sure to get something. The calling code doesn't always have to make sure that it is not a nullptr -> less errors in most cases. (In programming terms this called a "post-condition" and can be enforced e.g. with C++20 contracts :)

Disadvantage:
- It could be that in the future the need arises to find out if a given `UniformScalarFESpace` defines finite elements for a specific RefEl. If `nullptr` is returned, this is somehow handled by the code and maybe another backup FiniteElement is used. However, I think this is a very special case and the probability that we ever need it is probably small. And if we would need it, we could introduce an additional method `bool UniformScalarFESpace::definedFor(base::RefEl)` which returns true/false.

Are you fine with uncommenting the asserts in `UniformScalarFESpace`? (I don't know why they were commented)

**Comment by hiptmair** [comment]
It should be possible to skip entity types when defining a finite element space. Somehow the user of an `UniformScalarFESpace` object should have the possibility to find out whether for a certain entity type a reference element is available. Null pointers are a way to do this. The alternative would be a separate method.

**Comment by craffael** [comment]
I realized that there are actually many occasions where we need to check whether there is a finite element for a RefEl and where it is not enough if an assert fails: One common case is defining a finite element space only on triangles/edges but not on quads. Then ElementMatrixProviders of course have to initialize `PrecoumptedScalarReferenceFiniteElements` but they don't know a-priori whether there will be quadrilaterals in the mesh...
So I've decided to stick with the nullptr variant since it is probably the most used one.
