### ISSUE TITLE
GmshReader should not return const mesh

### ISSUE THREAD

**Issue by hiptmair** [craffael/lehrfempp#126]
The Gmhs reader should retrurn a mutable mesh, because codes may want to apply transformations on these meshes. Also refinement requires a non-const mesh. 

There is no reason, why the mesh should be const, since the reader will terminate and lerave the mesh alone.

**Comment by craffael** [comment]
GmshReader already provides such a method, see line 298 in gmsh_reader.h. 

> There is no reason, why the mesh should be const, since the reader will terminate and lerave the mesh alone.

This is not entirely correct: Besides the `mesh()` method, there are many other methods that establish the link between mesh entities and Gmsh's physical id's. So if you want to e.g. assemble a stiffness matrix with a coefficient that depends on the physical id, you cannot dispose the GmshReader after it has read the mesh. 

This implies that we can cannot change a "Gmsh mesh" in arbitrary ways after it was read in. E.g. if we would add additional entities or points, the GmshReader will be in an invalid state. Changing the coordinates of points is however fine, and I think this is what you want to do.

## General thoughts

From a software archictecture point of view it would be good if we could leave the mesh structure [**immutable**](https://en.wikipedia.org/wiki/Immutable_object). This is a very well known design principle: for example in Java the major GUI framework is based on immutable objects. Immutability has a lot of advantages (e.g. the GmshReader will always stay in a valid state) but of course it doesn't fit all purposes. In case of the mesh interface it's again a classical tradeoff between speed and software design:
- Making the mesh immutable would mean that in order to transform a mesh under a mapping we have to create a new mesh to achieve this. We could e.g. add a new method `std::shared_ptr<mesh> Mesh::Transform(std::function<Eigen::Vector2d(Eigen::Vector2d>) const` which returns a transformed version of the current mesh. From a design point of view this would be best, but it's of course not as fast as the next option.
- Accepting that a mesh is mutable we could implement a method `void Transform(...)` which would modifies the coordinates of the existing mesh. This is however not so trivial: We will have to wrap all geometry objects in new geometry objects. But because we can move instead of copy and because we don't have to copy the entity objects, it will be faster than the previous implementation.

**Comment by craffael** [comment]
Can I close the issue?

**Comment by hiptmair** [comment]
Please leave it open as a "TO BE DISCUSSED" when we tackle a major revision of LehrFEM++ this summer.
