### ISSUE TITLE
Gmsh reader should check mesh integrity

### ISSUE THREAD

**Issue by hiptmair** [craffael/lehrfempp#129]
There was a case when `GmshReader` reads a mesh without complaining, but the 'Mesh` object turned out to be broken: `checkMeshCompleteness` returned `false`.

**Comment by hiptmair** [comment]
This is the .msh file:

[circle.zip](https://github.com/craffael/lehrfempp/files/3068124/circle.zip)

**Comment by craffael** [comment]
Interesting, the point (0,0,0) appears twice in the gmsh file... I guess it was added manually in Gmsh...

As you point out, it probably makes sense to check for mesh completeness because I cannot think of a use case for incomplete meshes. I would however suggest to add this check not to the GmshReader but directly to the `MeshFactory::Build()` method, respectively in the Constructor of the `hybrid2d::Mesh`. There it could be incorporated into the algorithm and would not cause much overhead. Additionally we could be sure that every hybrid2d mesh is complete.
What do you think?

**Comment by hiptmair** [comment]
It is a good idea to incorporate the check in the `Build()` member function of `MeshFactory`. This rules out using 2D meshes with 1D parts. Actually, we could add a flag to `MeshFactory` to switch off the checking. By default the flag is on.

**Comment by craffael** [comment]
Good, I would suggest to put the flag into the constructor of the MeshFactory so we don't have to modify the MeshInterface for this. I will probably start to implement this in the next three days.

**Comment by anianruoss** [comment]
Unfortunately, this issue is not entirely resolved with #132: 

For second order elements, the `check_completeness` test fails because the midpoints of `SegmentO2` elements are not recognized. Moreover, for second order quadrilaterals, Gmsh writes `9-node second order quadrangle (4 nodes associated with the vertices, 4 with the edges and 1 with the face)` to the `.msh` file and the node associated with the face is also not recognized.

I had a look at the `check_completeness` code and I couldn't come up with an easy way to account for these cases. What one could do is to loop over all nodes and then to loop over all cells and check whether the output of `Global(AllPossibleNodesLocalMatrix)` has a column that is equal to the node. However, this is inefficient and not very generic as the local matrix possibly has to be adjusted if a new geometry object is added.  

Do you have an idea how I could solve this problem?

**Comment by craffael** [comment]
I'm working on this, there should be a fix by tomorrow (monday) evening. For the 9-order quadrangle an easy fix is to just ignore the 9th node. This should work in simple cases. In general it could happen that a 9-node mapping is well defined but a 8-node mapping is singular in which case we would need support for the 9-node mapping. Also its important to note that gmsh can produce 8-node quad meshes, see here: http://onelab.info/pipermail/gmsh/2014/009054.html and here http://onelab.info/pipermail/gmsh/2014/009057.html
