### ISSUE TITLE
Expensive copying of entities

### ISSUE THREAD

**Issue by hiptmair** [craffael/lehrfempp#17]
hybrid2d::Entuty contains the data members `std::unique_ptr<geometry::Geometry> geometry_` and `std::array<std::vector<size_type>, 2 - CODIM> sub_entities_`. How much effort does it involve to copy Entity objects? This is relevant, because there are quite a few scenarios where `Entity::SubEntities` is called in the inner loop during finite element assembly, for instance when accessing flags for edges. It seems that this entails copying of all sub-entities each time, which may be unduly expensive for an "inner-loop" operation.

**Comment by hiptmair** [comment]
Why don't we use plain and simple `Entity *` to store the sub-entities? This would circumvent the need for passing a pointer to a `Mesh` to the `hybrid2d::Entity` objects, which slightly breaks the logic of the code. 

Then it might be a good idea to introduce the derived Entity classes `Node`, `Edge`, `Trilateral`, and `Quadrilateral` for the topological entities of a 2D hybrid mesh. These classes could have simple `std::array` data members that store the pointers to sub-entities.

**Comment by hiptmair** [comment]
An option is to put the `Mesh` in charge of allocating and destroying `Geometry` objects. Thus, `Entities` can hold only a standard pointer. 

The pointers to `Geometry` objects would be initialized during mesh generation/mesh refinement, stored in a big dynamic vector, and the destructor of a `Mesh` object would then invoke a `delete` for all of them. Since allocation and release of Geometry objects would be confined to two places, this is reasonably safe.

**Comment by craffael** [comment]
Entities are actually not copyable, only moveable (Copy constructor is not defined) and moving entities is very cheap because the geometry + subEntity information is on the heap and only the pointer to it must be copied, not the content of the memory on the heap.

The reason that I didn't store `Entity*` pointers to the sub-entities has to do with how the algorithm in the constructor of the Mesh works: When the MeshBuilder passes the Mesh the nodes and elements, I don't know yet how many edges there will be. Hence the `lf::mesh::hybrid2d::Mesh::entities1_` vector might resize if not enough space was allocated in the beginning. This would then move all edges to another location on the heap and all `Entity<1>*` pointers from the elements to the edges would become invalid. I actually made this mistake in the beginning, it's not so nice to debug...

It would of course be possible to store `Entity*` pointers to the subentities if a two-phase algorithm is used. Of course would bring a small speed up but the small problem but after I spent 1.5h debugging the issue above I was a bit afraid that the same issue may happen again in a different context. If later on a programmer decides to add/remove an entity for some reason to the vector of entities, all pointers will become invalid!
