### ISSUE TITLE
LehrFEM++ aborts when reading large mesh

### ISSUE THREAD

**Issue by hiptmair** [craffael/lehrfempp#174]
When reading a very large large mesh [ZIP-file](https://polybox.ethz.ch/index.php/s/HRHLHXT8yw8koh1) a strange program abort is triggered:
~~~
***** Internal Program Error - assertion (n < nodes_.size()) failed:
/Users/amelieloher/.hunter/_Base/d45d77d/a04cd14/4577c35/Build/lehrfempp/Source/lib/lf/mesh/hybrid2d/mesh_factory.cc(58): node 4294967295 specified in call to AddEntity must be inserted with AddPoint() first.
~~~
However, the mesh has only 336266 nodes.

This problem was reported by Amelie Loher.

**Comment by hiptmair** [comment]
I have set up a branch `ReaderFactoryDebug` and a test code in `experiments/reader_factory_debug'. The output of the test run is 
~~~
reader_factory_debug $ ./experiments.reader_factory_debug.test 
***** Internal Program Error - assertion (n < nodes_.size()) failed:
/scratch/users/ralfh/NOSAVE/numpde/Numcourses/NumPDE/lehrfempp/lib/lf/mesh/hybrid2d/mesh_factory.cc(61): MeshFactory::AddEntity(EDGE): node 4294967295 specified in call to AddEntity must be inserted with AddPoint() first! nodes = [4294967295,4294967295] vs. nodes_.size() = 1244
Aborted (core dumped)
reader_factory_debug $ 
~~~
This is very strange because the mesh stored in `earth_refined.msh` contains 336266 nodes. It seems that the reader attempts to add an edge before all nodes are registered. Moreover the node number seems to be garbage from memory.

**Comment by hiptmair** [comment]
In the .msh file the 336266 nodes are listed in proper order as far as I can see, followed by 337584 triangular cells.

**Comment by craffael** [comment]
Okay I've investigated this and fixed it. However the underlying problem is that the mesh is not well connected: There are edges which do not belong to a triangle/quad.

Now GmshReader doesn't try to add an edge with node number unsigned(-1) anymore but later on the hybrid2d mesh factory will fail with an assertion. But at least the error message is much nicer :)
I've also added another unit test which will make sure that this doesn't happen again :)

Do you want me to update the NPDECODES repository so that it uses the newest version of LehrFEM++?

Btw. Are you simulating a virus spreading over the earth ? ;)

**Comment by hiptmair** [comment]
Thanks a lot. 

Amelie Loher is simulating ancient human migration on a global scale using the so-called Fisher/KPP reaction-diffusion model.

**Comment by hiptmair** [comment]
@craffael Since this is merely a fix and does not change any functionality and interfaces, it should be included in NPDECODES. Please ask Erick beforehand.

**Comment by craffael** [comment]
I've opened a PR on NPDECodes and asked Erick to review it :)
https://github.com/erickschulz/NPDECODES/pull/12
