### ISSUE TITLE
Speaking typenames

### ISSUE THREAD

**Issue by hiptmair** [craffael/lehrfempp#31]
I propose to use a few "telling types" that all boil down to `unsigned int`

- size_type : type for the length of vectors/arrays, size of containers, numbers of objects, etc.
- dim_t : (co-)dimensions (usually a small integer, also to be used for numbers of sub-entities
- glob_idx_t : global index of an entity of the mesh
- loc_idx_t: local index of a sub-entity or a degree of freedom

Using these typenames would considerably enhance the readability of the code.

**Comment by craffael** [comment]
I agree, I think it would make sense to put same fundamental types into the `lf` or `lf::base` namespace. I think that `size_type`, `dim_t` and `loc_idx_t` make sense. I'm however not so happy with the name of `loc_idx_t`: I associate the term "local" with the reference element ("local coordinates") but the index of a sub-entity w.r.t. the parent entity has nothing to do with the reference element or the mapping local -> global. I think `sub_idx_t` would be more appropriate?

Finally, I wouldn't introduce `glob_idx_t` at all because it's natural to compare the index of an entity (`glob_idx_t`) with the the total number of entities (`size_type`) (i.e. in order to determine if the index is out of range in an assert statement). And comparing two objects with each other that have conceptually a different meaning sounds a bit strange to me (e.g. as an example: it also doesn't make sense to compare `dim_t` with `size_type`).

**Comment by hiptmair** [comment]
- `sub_idx_t` is a better typename, indeed. 
- Loop variables and loop bounds are inherently different kinds of objects, but invariably they are compared. So different types for these objects are nothing awkward as long as a comparison makes sense, which is clearly the case for `size_type` and `glob_idx_t`.

**Comment by hiptmair** [comment]
The use of "telling" typenames in LehrFEM++ is not really consistent up to now. Some of the types are separately introduced in different namespaces and they are not used wherever they should be used.

I propose the following types:
- `size_type = unsigned int`; number of objects, length of vectors, etc.
- `glb_idx_t = unsigned int`: index of entities
- `sub_idx_t = unsigned int`: local indices of sub-entities
- `dim_t = unsigned int`: co-dimensions, dimensions
- `dof_idx_t = unsigned int`: indices for  global coefficient vectors
- `loc_idx_t = unsigned int`: for indexing entries of element matrices and vectors.
- `glb_coord_t = Eigen::VectorXd`: world coordinates of a point
- `ref_coord_t = Eigen::VectorXd`: reference coordinates of a point
- `packed_glb_coord_t = Eigen::MatrixXd`: matrix whose columns contain coordinates
- `packed_ref_coord_t = Eigen::MatrixXd`: matrix whose columns contain reference coordinates

These types could be put into a namespace `lf::types`, which is included by all other modules. It may even be acceptable to do `using namespace lf::types;`.

For learners these telling types are a great help to understand the different meanings, e.g., of indices. 

Can these types be introduced conveniently using some IDE?

**Comment by hiptmair** [comment]
Some of the type are already defined in `base.h`.

**Comment by craffael** [comment]
I would like to point out that I'm not a big fan of using typedefs for documentational purposes because:
1. If I see the signature `packed_glb_coord_t Global(const packed_ref_coord_t& local) const` it's not clear to me what the type of `local` is, is it a fixed/dynamic matrix, a std::vector? I have to check the doxygen documentation first. Same problem is for `glb_coord_t`
2. A similar problem arises when I look at the return type of `Global`: Just by looking at the signature I don't know whether I have to call `Global(local).size()` or `Global(local).cols()` to get the number of mapped points.
3. If I want to say that a parameter is e.g. an eigen matrix whose columns contain reference/local coordinates, I would much rather name the parameter itself `local` so that it is clear that it is in local coordinates. (i.e. implicit documentation by parameter names, not by parameter types)
4. Writing new code for LehrFEM++ becomes more complex: When I want to code for LehrFEM++ I need to have this list of 10 typedefs printed out so that I can always select the right type. This is especially a problem for contributors that are new or that only want to contribute a small fix.
5. So far I haven't seen a single c++ library that uses typedefs for this purpose. I think it's a very uncommon use case. As far as I know, global typedefs are mostly used for template metaprogramming and sometimes to make sure that e.g. an `int` is always 32-bit (e.g. `std::size_type`)
6. Because of the previous two points, I also suspect that it will be rather hard to make sure that the correct types are used throughout the code in a consistent fashion. I think most people will either use `auto` or e.g. `unsigned int`.

Maybe we could also ask the students working on LehrFEM++ what they prefer and what makes the code easier for them to read?

If you insist on using typedefs for this use case we can of course try to go for it. But because we cannot simply replace every `unsigned int` with `glb_idx_t`, it's hard to automated this task, even with an IDE. Someone will have to read through the whole code and replace the types...

Finally, I wouldn't put the typedefs into another namespace because strictly speaking this would also mean introducing yet another cmake library (if we want to be consistent with the rest of the code).

**Comment by hiptmair** [comment]
Valid points. So let us postpone sweeping changes to the library. Since some of the type are used right now, can we go for that `namespace lf::types` which collects the typedefs and documents them? Why does this have to do anything to do with `cmake`? I thought, namespaces were just a tool to organize logical units of data types and also a way to make those available without qualification via `using`. Is this old-fashioned C++ thinking? 

By the way, I do not expect the user of the library to use the typedefs. They are chiefly meant to enhance the readability of the source code of the library.

**Comment by craffael** [comment]
Yeah I would really reconsider whether it is a good idea to introduce such a huger number of typedefs just for documentational purposes.
Concerning the namespace: introducing the namespace `lf::types` is of course not old-fashioned c++ thinking, actually most c++ libraries don't have this [1-to-1 relation between namespaces, folders and CMake targets](https://craffael.github.io/lehrfempp/modules_.html). I've introduced this relationship in LehrFEM++ because many other languages enforce or at least suggest such a structure. It simplifies many things and I think it's also not such a bad idea for C++ (some boost libraries also use a similar structure):
- if the linker complains that a symbol was not found, it's immediately clear where this symbol should come from (folder/cmake target)
- if it is known in what namespace a class lies, it's also clear where we have too look for the corresponding header/source file
- if we want to include a class, it's clear what header we have to include (the corresponding module/namespace master header file)

if we introduce the namespace `lf::types` e.g. in the file `lf/base/types.h` we loose some of these advantages:
If somebody needs the type `lf::types::dim_t` what header file should he include? In what file can he find the definition of `lf::types::dim_t`?

Finally I should maybe also mention that I think it would be better to introduce the typedefs where they are used. e.g. 
- `size_type` is a fundamental type that is used throughout LehrFEM++, therefore I would put it into `lf::base`
- `glb_idx_t` and `sub_idx_t` are related to indices of entities, so I would put them into `lf::mesh`
- `dim_t` is related to RefEl which belongs to `lf::base` -> put it into `lf::base`

A namespace `lf::types` would be quite different from all the other namespaces that we have in LehrFEM++ because it doesn't group code elements together that fulfill some purpose (e.g. represent a mesh, provide geometry mappings, quadrature rules). It would be just a namespace for typedefs. (Consequently one could argue that we should also make the namespaces `lf::classes` and `lf::functions` ;))

**Comment by craffael** [comment]
(I just realized that I also introduced two typedefs myself: `dim_t` and `quadOrder_t`. Somehow I always have this illusion that I can change the type of these typedefs later on but, this makes of course hardly ever sense.)

**Comment by hiptmair** [comment]
Then let us keep the current structure. I will do some tidying up of the typedefs.
