### ISSUE TITLE
Lightweight Range

### ISSUE THREAD

**Issue by hiptmair** [craffael/lehrfempp#43]
As demonstrated by the test code `lf.experiments.efficiency.runtime_test`, it would be very desirable to have an efficient lightweight range at one's disposal in LehrFEM++. Such a range should be constructible from two pointers to objects of the base type defining a linear array. It should be compatible with `foreach` loops and also offer access through `[]` and `at` like `std::vector`. Moreover, it should also have a `size()` method telling the number of elements in the range. 

Internally a lightweight range need store only two pointers. Of course, it will be invalidated once the underlying array ceases to exist.

**Comment by hiptmair** [comment]
See the  [discussion](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2018/p0944r0.html) about the support for contiguous data layout.

**Comment by craffael** [comment]
> 
> 
> See the [discussion](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2018/p0944r0.html) about the support for contiguous data layout.

I fully agree with that proposal. It seems that it has been merged into the [one range proposal](http://93.90.116.65/JTC1/SC22/WG21/docs/papers/2018/p0896r3.pdf) which has been merged into C++20. Moreover c++20 will add [`std::span`](https://en.cppreference.com/w/cpp/container/span) which is also somewhat related to this proposal.

**Comment by craffael** [comment]
I'm not sure this is the right spot to post this because I feel that we have discussed this topic also multiple times on other occasions. But to summarize, I think the current implementation of ForwardRange/RandomAccessRange has the following drawbacks:

1) It introduces additional overhead, most notably dynamic_casts, see #97 .
2) The code is quite complicated to understand because it relies on type erasure.
3) The corresponding classes are missing thorough doxygen documentation.

Problem 1) could be remedied mostly by using small object optimization and by getting rid of unnecessary dynamic_cast's. But this would make the code even more complex and even harder to understand.

I can see two possible alternatives:
1) just use std::vector<Entity*> all the time. In c++20 this could be replaced by [`std::span`](https://en.cppreference.com/w/cpp/container/span).
2) Wait until C++20 and replace all virtual interface classes with [C++20 Concepts](https://en.wikipedia.org/wiki/Concepts_(C%2B%2B)), respectively C++20 ranges.


### Alternative 1): std::vector (of pointers)
I think this is more or less what you originally proposed with this issue which is more or less a `std::vector`. Therefore I would go with an `std::vector` directly which is a well-documented and battle-proven class.

Personally I don't like this option a lot because it doesn't provide the best performance and because it involves raw pointers. To understand the first point (performance), consider e.g. a `std::vector<Entity*>` as it would be returned by a call to `Mesh::Entities(1)`. The current mesh implementation stores all the segments in one contiguous array, but because we only get a vector of pointers, the compiler has no way of knowing that this is in fact the case. He has to assume that every entity could be stored at a completly different location in memory. So when we want to loop over all segments of the mesh, we have to loop over the vector of pointers and then everytime we have to dereference the pointer.
This is much more overhead than if we could just iterate over a `std::vector<Entity>` directly. (pointer-addition vs. (pointer-addition + dereference operation)). I'm not sure if memory locality also suffers, probably this depends on the cache size of the cpu.

Nevertheless, I expect that an implementation based on `std::vector<Entity*>` would still be faster than the current type-erasure-implementation. I think the biggest advantage of just using `std::vector<Entity*>` is that it is easier to grasp and understand. In terms of performance we can probably not get more than 20% speedup (#97).

### Alternative 2) C++20 Concepts
C++20 introduces [Concepts](https://en.wikipedia.org/wiki/Concepts_(C%2B%2B)), which has been on my wishlist for a very long time. What's more the STL introduces [Range concepts](https://en.cppreference.com/w/cpp/ranges) which are compile-time versions of what I've implemented + a lot more.

This would be my preferred solution because it comes without compromises in terms of speed and also offers the flexibility that we currently have in the library. The only problem is that it will probably not land before the Spring semester 2020 or at least not on all platforms. I think at some point it would be interesting to consider to replace all the current abstract virtual interface classes with C++20 concepts, but at the moment it's just too early.

### Conclusions
I would suggest to start implementing Option 1) (vector of pointers) now which shouldn't be more than a day of work. In about a year we could start to think about supporting C++20 concepts. 
Does this sound right? Did I miss something or is something unclear?

**Comment by hiptmair** [comment]
Thanks for the wealth of information. This issue requires thorough discussion. I am not particularly fond of the 'std::vector' solution, because we need not store pointers, if it is known that the referenced objects are stored contiguously in an array. Hence, it is sufficient to store only two pointers.

**Comment by craffael** [comment]
What I had in mind with the std::vector approach was that the `Mesh::Entities()` method would have the following signature:
```
const std::vector<const Entity*>& Entities(unsigned codim) const;
```

which would e.g. allow us to write
```
for(auto& ep : mesh.Entities(0)) {  ... } // doesn't copy the whole array of pointers
```

But what I forgot a bit is that if a user writes
```
auto entities = mesh.Entities(0);
for(auto& ep : entities) { ... }
```
then indeed all pointers will be copied which is of course not very wise.

So if we don't want to wait until C++20 Concepts/Ranges we should probably use a special struct, as you suggest, which stores two pointers  (respectively a pointer + a size) and which we can use to enumerate over a `std::vector<const Entity*>`. I think this is more or less the idea of [std::span](https://en.cppreference.com/w/cpp/container/span) which is part of C++20.  There is also a backport to earlier versions of C++20 available: https://github.com/martinmoene/span-lite .So an option would be to include this header-only library in lehrfempp until we make the switch to C++20.

**Comment by hiptmair** [comment]
span-lite seems to be an interesting option until C++20 becomes available.

**Comment by craffael** [comment]
What remains to be done is to emplz std::span for traversing mesh entities. This entails changing all loops

**Comment by craffael** [comment]
I mark this as resolved since we changed everything to std::span.
