### ISSUE TITLE
ChildGeometry() in Geometry

### ISSUE THREAD

**Issue by hiptmair** [craffael/lehrfempp#6]
For the flexible implementation it seems indispensible to provide the Geometry interface class with a method `virtual std::unique_ptr<Geometry> ChildGeometry(int ref_pattern,const std::vector<std::unique_ptr<Geometry> sub_geometries) const;`. This method is supposed to generate the geometry for a child entity created by subdividing the current entity. The argument `ref_pattern` passes a code selecting the type of refinement and the concrete child entity, whose geometry is requested. Of course, passing an integer for this sake is not really elegant, but all possible refinement patterns are not known at the time of writing the Geometry interface. The second argument is an array of pointers to the Geometry objects belonging to subentities of the next higher co-dimension. This information might be needed when using polynomial parameterizations when approximating exact parameterizations of boundaries.

**Comment by craffael** [comment]
I think it's in principle a very good idea to add the method `ChildGeometry()` because it allows us to separate the part of the refinement logic that is related to geometry approximation from the part that is purely topological. At the moment I'm not 100% sure about the two parameters for the `ChildGeometry()` method:

1. `ref_pattern`: Here I would suggest to not pass an integer or an enum because
    - as you say there are many different refinement patterns. hp-theory also considers refinement patterns where the entities are not cut in the middle but closer to the singularity. In this case there would be even infinitely many refinement patterns...
    - if we decide to support another refinement pattern at a later time, we will have to change each and every geometry implementation, this is not extensible. 

At the moment I can think of at least one better alternative:
  - Pass another geometry object that maps from the child entity to the father entity (both in reference coordinates). E.g. if we want to subdivide a Quad into 4 smaller congruent quads, we could pass the first-order mapping that maps the nodes (0,0),(0.5,0),(0.5,0.5),(0,0.5) to (0,0),(1,0),(0,1),(1,1). So we would pass a geometry object that is known in DUNE as "geometryInFather". The are two big advantages of this approach: First, it is very very flexible and allows any refinement pattern; if the Refiner wants to split the entity in four child entities, he calls this method simply four times. Second, I think the refiner class should anyway provide the user with a geometryInFather mapping so we can reuse it directly here.

2. `sub_geometries`: Here the situation is less clear. I think passing an array of (pointers to) `codim=1` sub-geometries is one way to solve the problem. I can see two (small) disadvantages/problems:
    - Geometry Objects that don't touch a paramterized surface are purely first order and passing the second parameter is not needed. We could agree that we can also pass `nullptr`'s for the sub-geometries for such cases. 
    - Geometry objects that can represent the surface exactly (e.g. by NURBS) also don't need this information.

An alternative to passing the `sub_geometries` while calling `ChildGeometry()` is to pass the `sub_geometries` already when the geometry object is constructed. This would simplify the implementation of the Refiner class considerably because it doesn't have to know anything about the exact surface representation. It would be the task of the MeshBuilder (e.g. GmshReader) to construct the  geometry objects such that they already contain an exact description of the faces.

**Comment by hiptmair** [comment]
Imagine the following situation, which is fairly realistic in the case of polynomial boundary approximation (e.g. isoparametric finite elements): The edges come with an exact parameterization, but the elements employ only a polynomial approximatiion. Thus, when refining an element, the children cannot just be pieces of the parent entity, but they will have to be built also based on information contained in the edges. This is why I would like  to see a vector of pointers to subentities of the next higher co-dimension passed in the argument list of `ChildGeometry()`. In my opinion the `geometryInFather()` approach imposes too many a priori restrictions. This is why nother better  than passing a generic integer selection flag came to my mind.

**Comment by hiptmair** [comment]
The code should be ready to deal with many ways of local refinements that we cannot imagine yet!

**Comment by craffael** [comment]
Maybe there was a misunderstanding in how I described my suggestions. I'm aware of the fact that the ChildGeometry() method must know the exact shape of the codim+1 sub-entities and my suggestion is to solve this not by adding another parameter to the `ChildGeometry()` method, but by adding an additional parameter to the constructor of the concrete Geometry classes.

E.g. instead of constructing a `QuadO1` only with the coordinates of the four corners, we pass additionally 4 codim=1 geometry objects that describe the exact shape of the four edges of the `QuadO1`. In this way the QuadO1 object knows from the beginning how the four edges look exactly (i.e. it knows that they are not straight). When we then call `ChildGeometry()` we don't have to pass the these 4 codim=1 geometry objects again because the QuadO1 has them already stored. The advantage of this is, that the user that calls `ChildGeometry()` doesn't have to know anything about the exact shape of surfaces which makes the refinement routines much simpler. In some sense this outsources the responsibility for providing an accurate boundary description to the mesh constructor (e.g. the GmshReader) which I think is also where it belongs.

A final word about the `geometryInFather()` concept: If the father geometry approximates the boundary only, then "fatherGeometry(geometryInFather(x)) != childGeometry(x)". So the geometryInFather _cannot_ be used to construct the `childGeometry` in this case. I know that in the past I've often argued that the child geometry could be constructed like that, but of course, this is not true for geometry elements that lie on the boundary. But this doesn't pose a problem to the proposed solution: Every class that implements the Geometry interface can implement the `childGeometry()` in a different way and can in particular take into account additional information about the boundary.

**Comment by hiptmair** [comment]
Works well in the implemented refinement routines.
