### ISSUE TITLE
Indices managed by Mesh

### ISSUE THREAD

**Issue by hiptmair** [craffael/lehrfempp#8]
The indexing of entities should be managed by the global Mesh object, because a local entitiy has no idea about its role in the larger mesh. Hence the Index() method should be kept in the Mesh interface class.

**Comment by craffael** [comment]
I think there are arguments for putting the Index() method into the Mesh class and for putting it into the Entity class. It depends on how we think of an Entity object:

### Put `Index()` method to Mesh class
In this case we interpret the index as an additional piece of information that we attach to a given entity. Similarly, we could argue that the geometric description of an entity is also an additional piece of information and we could move the geometry() method also to the Mesh class. This resembles very much the [style of programming that is used in C to implement Object Oriented design](https://www.codementor.io/michaelsafyan/object-oriented-programming-in-c-du1081gw2).

Advantages:
- Conceptually the index can be interpreted as a mathematical map that assigns to every entity a unique integer.
- Conceptually an entity object is a very simple object that is linked to other entities. The entity itself doesn't have any inherent properties at all.

Disadvantages:
- Just looking at the definition of the Entity interface, it's not obvious that every entity also has an index (and a geometry object).

### Put `Index()` method into Entity class
In this case we have to interpret an entity as an object that contains pointers to sub entities, that has a unique integer (index) and (possibly) a geometric realization.

Advantages:
- By looking at the definition of the Entity interface it is clear what the user can do with such an object.

Disadvantages:
- Its still not clear how to get the largest possible index starting from a given entity.
- It seems as if the index is an inherent property of an entity.

### Bottomline
I can live with both approaches but I slightly prefer the latter because I think that the index is a "universal" property of an entity that is used by every fem code. Other properties that can also be attached to an entity such as material properties or basis functions are less universal and depend on the problem at hand. For such properties it makes absolutely sense to store them in a separate data structure.
